// Generated by scripts/sync-version.mjs. Do not edit.
export const CURRENT_RELEASE = {
  "version": "0.2.1",
  "date": "2026-07-18",
  "changes": [
    "Added a no-setup Agent Teams wizard.",
    "Added team lead, researcher, developer, test engineer, and code reviewer roles.",
    "Made teams, members, tasks, and activity events persistent.",
    "Connected Agent Team permission levels to real coding-agent permission modes.",
    "Improved agent-to-agent routing and provider environment isolation.",
    "Completed GitHub Release-based auto-updates and version synchronization."
  ]
} as const
