// Generated by scripts/sync-version.mjs. Do not edit.
export const CURRENT_RELEASE = {
  "version": "0.2.1",
  "date": "2026-07-18",
  "changes": [
    "Teknik ayar gerektirmeyen Agent Teams sihirbazı eklendi.",
    "Takım lideri, araştırmacı, geliştirici, test uzmanı ve kod inceleyici rolleri eklendi.",
    "Takımlar, üyeler, görevler ve çalışma olayları kalıcı hale getirildi.",
    "Agent Team yetki seviyeleri gerçek Claude Code permission modlarına bağlandı.",
    "Agent-to-agent yönlendirme ve provider ortam izolasyonu güçlendirildi.",
    "GitHub Release tabanlı otomatik güncelleme ve sürüm senkronizasyonu tamamlandı."
  ]
} as const
