import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const readJson = async (name) => JSON.parse(await readFile(join(root, name), 'utf8'))
const writeJson = async (name, value) => writeFile(join(root, name), `${JSON.stringify(value, null, 2)}\n`, 'utf8')

const release = await readJson('release-manifest.json')
if (!/^\d+\.\d+\.\d+$/.test(release.version)) throw new Error('release-manifest.json version must use semantic versioning')
if (!/^\d{4}-\d{2}-\d{2}$/.test(release.date)) throw new Error('release-manifest.json date must use YYYY-MM-DD')
if (!Array.isArray(release.changes) || release.changes.length === 0 || release.changes.some((item) => typeof item !== 'string' || !item.trim())) {
  throw new Error('release-manifest.json must include at least one release note')
}

const pkg = await readJson('package.json')
pkg.version = release.version
await writeJson('package.json', pkg)

const lock = await readJson('package-lock.json')
lock.version = release.version
if (lock.packages?.['']) lock.packages[''].version = release.version
await writeJson('package-lock.json', lock)

const generated = `// Generated by scripts/sync-version.mjs. Do not edit.\nexport const CURRENT_RELEASE = ${JSON.stringify(release, null, 2)} as const\n`
await writeFile(join(root, 'src/renderer/src/generatedRelease.ts'), generated, 'utf8')

const installerName = `TermFlow-${release.version}-x64.exe`
const installerUrl = `https://zomlia6emkmpi3hi.public.blob.vercel-storage.com/downloads/${installerName}`
const indexPath = join(root, 'website/index.html')
let index = await readFile(indexPath, 'utf8')
index = index.replace(/TermFlow-\d+\.\d+\.\d+-x64\.exe/g, installerName)
await writeFile(indexPath, index, 'utf8')

const mainPath = join(root, 'website/main.js')
let main = await readFile(mainPath, 'utf8')
main = main
  .replace(/v\d+\.\d+\.\d+\/TermFlow-\d+\.\d+\.\d+-x64\.exe/g, `v${release.version}/${installerName}`)
  .replace(/\.\/download\/TermFlow-\d+\.\d+\.\d+-x64\.exe/g, `./download/${installerName}`)
  .replace(/installer:\s*'[^']+'/g, `installer: '${installerUrl}'`)
await writeFile(mainPath, main, 'utf8')

console.log(`Version surfaces synchronized to ${release.version}`)
